"use strict";

const path = require("path");
const siteMetadata = require("./src/metadata.json");

module.exports = {
  siteMetadata,
  plugins: [
    `gatsby-plugin-typescript`,
    `gatsby-plugin-styled-components`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    // reference: https://www.gatsbyjs.org/packages/gatsby-plugin-react-helmet
    "gatsby-plugin-react-helmet",
    "gatsby-plugin-postcss",
    `gatsby-plugin-offline`,
    {
      resolve: `gatsby-plugin-purgecss`,
      options: { tailwind: true },
    },
    // images
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: path.join(__dirname, `src`, `assets/images`),
      },
    },
    // blog
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `blog`,
        path: path.join(__dirname, `content`, `blog`),
      },
    },
    //references:
    // https://www.gatsbyjs.org/packages/gatsby-plugin-react-svg/
    // https://github.com/jacobmischka/gatsby-plugin-react-svg
    // https://github.com/jhamlet/svg-react-loader
    {
      resolve: "gatsby-plugin-react-svg",
      test: /\.svg$/,
      options: {
        rule: {
          include: /assets\/images\/svg\//,
        },
      },
    },
    {
      resolve: "gatsby-plugin-stylelint",
      options: {
        configFile: ".stylelintrc",
        emitErrors: false,
        files: ["src/**/*.?(pc|sc|c|sa)ss"], // pcss|scss|css|sass
      },
    },
    // reference: https://www.npmjs.com/package/gatsby-plugin-sitemap
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/sitemap.xml`,
        // Exclude specific pages or groups of pages using glob parameters
        // See: https://github.com/isaacs/minimatch
        // The example below will exclude the single `path/to/page` and all routes beginning with `category`
        exclude: ["/elements"],
        query: `
        {
          site {
            siteMetadata {
              siteUrl
            }
          }

          allSitePage {
            edges {
              node {
                path
              }
            }
          }
      }`,
      },
    },
    // reference: https://www.gatsbyjs.org/packages/gatsby-plugin-manifest
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: siteMetadata.title,
        short_name: siteMetadata.title,
        description: siteMetadata.description,
        start_url: `/`,
        background_color: "#242942",
        theme_color: "#2a2f4a",
        display: `minimal-ui`,
        icon: "src/assets/images/svg/developassion-symbol.svg", // This path is relative to the root of the site.
        //theme_color_in_head: false, // This will avoid adding theme-color meta tag.
        // TODO add other icons
        // icons: [
        //   {
        //     src: "icons/icon_512x512.png",
        //     sizes: "512x512",
        //     types: "image/png",
        //   },
        //   {
        //     src: "icons/icon_192x192.png",
        //     sizes: "192x192",
        //     types: "image/png",
        //   },
        // ],
      },
    },
    // reference: https://www.gatsbyjs.org/packages/gatsby-plugin-netlify/
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {
          "/*": [
            // The CSP is generated by gatsby-plugin-csp and added to the _headers file in public/ before publish.
            // That is handled by the build:prod script which executes csp-util.js, which looks for the token below.
            "Content-Security-Policy: __REPLACE_ME__",
            //"Access-Control-Allow-Origin: null",
            //"Clear-Site-Data: *" // useful for logout pages: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data

            // reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
            // Not yet ready for prime time
            "Feature-Policy: autoplay 'none'; camera 'none'",
            "Referrer-Policy: strict-origin",
            "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload",
            "Upgrade-Insecure-Requests: 1",
            "X-Content-Type-Options: nosniff",
            "X-DNS-Prefetch-Control: on",
            "X-Download-Options: noopen",
            "X-Frame-Options: DENY",
            "X-Permitted-Cross-Domain-Policies: none",
            "X-XSS-Protection: 0",
          ],
        }, // option to add more headers. `Link` headers are transformed by the below criteria
        allPageHeaders: [], // option to add headers for all pages. `Link` headers are transformed by the below criteria
        mergeSecurityHeaders: true, // boolean to turn off the default security headers
        mergeLinkHeaders: true, // boolean to turn off the default gatsby js headers
        mergeCachingHeaders: true, // boolean to turn off the default caching headers
        generateMatchPathRewrites: true, // boolean to turn off automatic creation of redirect rules for client only paths
      },
    },
    // Reference: https://www.gatsbyjs.com/plugins/gatsby-plugin-csp/
    {
      resolve: `gatsby-plugin-csp`,
      options: {
        disableOnDev: false,
        mergeScriptHashes: true,
        mergeStyleHashes: false,
        mergeDefaultDirectives: false,
        // references:
        // https://content-security-policy.com/
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
        // https://scotthelme.co.uk/csp-cheat-sheet
        directives: {
          "base-uri": "'self'",
          "block-all-mixed-content": "",
          "child-src": "'self'",
          // FIXME replace develop script with "develop": "gatsby develop --status-port 8089",
          // as soon as the --status-port parameter is supported: https://www.gatsbyjs.com/docs/gatsby-cli/
          // Set a fixed port for the Socket.IO debugging port: https://github.com/gatsbyjs/gatsby/pull/25862/commits/2e3e5bbf1e0eaf3ee462d2f1a3fd2a7c94b57a7c
          "connect-src": "'self' http://localhost:8000 http://localhost:8089", // WARNING: MUST be aligned with csp-util.js
          "default-src": "'self'",
          "disown-opener": "",
          "font-src": "'self' data: https://fonts.gstatic.com",
          "form-action": "'none'", // FIXME to adapt for Hubspot?
          //"frame-ancestors": "'none'", // cannot be used if CSP defined using a meta tag
          "frame-src": "'self'",
          "img-src": "'self' data: www.google-analytics.com",
          "manifest-src": "'self'",
          "media-src": "'self'",
          "object-src": "'self'",
          "plugin-types": "application/pdf",
          "prefetch-src": "'self'",
          sandbox: "",
          "script-src": "'self' www.google-analytics.com 'sha256-KWO6UOhc/cfhZd4gtXYPu4WkSRPuCQDtCkF/v9OyJB8='",
          "style-src": "'self' 'unsafe-inline' blob: https://fonts.googleapis.com",
          "upgrade-insecure-requests": "",
          "worker-src": "'self'",
        },
      },
    },

    // reference: https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: "G-Y1EM8E6B3T",
        // Puts tracking script in the head instead of the body
        head: false,
        // Setting this parameter is optional
        anonymize: true,
        // Setting this parameter is also optional
        respectDNT: true,
        // Avoids sending pageview hits from custom paths
        exclude: [],
        // Enables Google Optimize using your container Id
        //optimizeId: "YOUR_GOOGLE_OPTIMIZE_TRACKING_ID",
        // Enables Google Optimize Experiment ID
        //experimentId: "YOUR_GOOGLE_EXPERIMENT_ID",
        // Set Variation ID. 0 for original 1,2,3....
        //variationId: "YOUR_GOOGLE_OPTIMIZE_VARIATION_ID",
        // Any additional create only fields (optional)
        //sampleRate: 5,
        //siteSpeedSampleRate: 10,
        //cookieDomain: "dev-concepts.dev", // auto
      },
    },
    // reference: https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure
    {
      resolve: "gatsby-plugin-react-axe",
      options: {
        showInProduction: false,
        axeOptions: {
          // Your axe-core options.
        },
      },
    },
  ],
};
